language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t omarjmedina/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true omarjmedina/docker-test npm run test

after_success:
  - docker build -t omarjmedina/multi-client ./client
  - docker build -t omarjmedina/multi-nginx ./nginx 
  - docker build -t omarjmedina/multi-server ./server
  - docker build -t omarjmedina/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push omarjmedina/multi-client
  - docker push omarjmedina/multi-nginx
  - docker push omarjmedina/multi-server
  - docker push omarjmedina/multi-worker
